### ISSUE TITLE
Add Announcemnt info?

### ISSUE THREAD

**Issue by Apollon77** [rithvikvibhu/GHLocalApi#124]
In the Google Home APp you can do an announcement on a device ... Does anyone discovered how to send it to the device?

**Comment by rithvikvibhu** [comment]
There are 2 ways to do it generally:
1. The announce that works with Google Assistant (where you ask Google from another device like a phone, to say something on the GH device at home, etc.) This - like other Google Assistant features - goes through Google's servers and won't be documented in this API since this is only for local communication. If you really want to dig into it and make it work, see https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-644959103 and https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-650590500
2. Use something like https://github.com/vervallsweg/cast-web-api that does text-to-speech and then plays it with Cast like normal audio. It's relatively easier and is enough for most cases.
