### ISSUE TITLE
decode proto script not working anymore

### ISSUE THREAD

**Issue by iamatulsingh** [rithvikvibhu/GHLocalApi#126]
I was checking the decode proto script from https://gist.github.com/rithvikvibhu/1a0f4937af957ef6a78453e3be482c1f but it's not working anymore. Have somebody spent time on it? It seems var2['7'] is not a array anymore. If anyone can share old proto file then I can check it once.

**Comment by rithvikvibhu** [comment]
Wow, looking at that script from years ago and that horrible code 💀

I was thinking of redoing that with a more fuzzy/tolerant search instead of hard-coded indexes but never got around to it.

You can probably use `protoc --decode_raw` and find a string that looks like a 103 or 105 or 108 char length (don't remember exactly) and doesn't contain any weird symbols other than slashes and maybe underscores.

It's likely "near" an email address, but that could've changed too.

I don't have a rooted Android to get that file, but if anybody sends one, I can try to fix/rewrite that script (or if anyone does that too, am happy to link to it from the docs!)

**Comment by iamatulsingh** [comment]
Thanks, I'll have a look.

**Comment by iamatulsingh** [comment]
In the script, it's written to read array from the key 7 `if (val2['7'] && Array.isArray(val2['7']))` but it appears to be a `Buffer` and not an array. I tried `protoc --decode_raw` and appears to be a object. Still no idea how to read it. Do you have any rough idea?

One more question: Token is in base64 format?

**Comment by iamatulsingh** [comment]
I tested that base64 token with `curl -H "cast-local-authorization-token: Qx8+kToXXXXXXXXXXXXGuFhACQ=" -vv --insecure https://192.168.2.124:8443/setup/bluetooth/scan_results | jq` but I'm getting `HTTP/1.1 401 Unauthorized` and there are no other string which is 108 char long.
